# Generated by Django 5.0.1 on 2024-04-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_quantity_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_name',
            new_name='name',
        ),
    ]
