# Generated by Django 5.0.1 on 2024-04-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_product_name_cartitem_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
